s = set()
n = input("Enter a Number: ")
s.add(n)
n = input("Enter a Number: ")
s.add(n)
n = input("Enter a Number: ")
s.add(n)
n = input("Enter a Number: ")
s.add(n)
n = input("Enter a Number: ")
s.add(n)
n = input("Enter a Number: ")
s.add(n)
n = input("Enter a Number: ")
s.add(n)
n = input("Enter a Number: ")
s.add(n)
print(s)