a = input("Enter First Number:\n")
b = input("Enter Second Number:\n")
n1 = int(a)
n2 = int(b)
print(f"The sum of {n1} and {n2} is {n1+n2}")
print(f"The product of {n1} and {n2} is {n1*n2}")
print(f"The difference of {n1} and {n2} is {n1-n2}")
print(f"The division of {n1} and {n2} is {n1/n2:.2f}")
print(f"The floor division of {n1} and {n2} is {n1//n2}")
print(f"The Modulo of {n1} and {n2} is {n1%n2}")
print(f"The exponential power of {n1} to {n2} is {n1**n2:.2e}")
